

ALTER TABLE IF EXISTS ONLY public.job DROP CONSTRAINT IF EXISTS fkpaipfyvwj7fo654ri6uuvx6he;
ALTER TABLE IF EXISTS ONLY public.job_skill DROP CONSTRAINT IF EXISTS fkj33qbbf3vk1lvhqpcosnh54u1;
ALTER TABLE IF EXISTS ONLY public.job_skill DROP CONSTRAINT IF EXISTS fk9ix4wg520ii2gu2felxdhdup6;
ALTER TABLE IF EXISTS ONLY public.skill DROP CONSTRAINT IF EXISTS skill_pkey;
ALTER TABLE IF EXISTS ONLY public.job_skill DROP CONSTRAINT IF EXISTS job_skill_pkey;
ALTER TABLE IF EXISTS ONLY public.job DROP CONSTRAINT IF EXISTS job_pkey;
ALTER TABLE IF EXISTS ONLY public.entreprise DROP CONSTRAINT IF EXISTS entreprise_pkey;
DROP TABLE IF EXISTS public.skill;
DROP TABLE IF EXISTS public.job_skill;
DROP TABLE IF EXISTS public.job;
DROP TABLE IF EXISTS public.entreprise;
SET default_tablespace = '';



--
-- Name: entreprise; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.entreprise (
    id bigint NOT NULL,
    adresse character varying(255),
    description text,
    email character varying(255),
    nom character varying(255),
    secteur character varying(255),
    telephone character varying(255),
    ville character varying(255)
);


ALTER TABLE public.entreprise OWNER TO postgres;

--
-- Name: entreprise_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.entreprise ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entreprise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job (
    date_candidature date,
    date_expiration date,
    date_lancement date,
    date_reponse date,
    entreprise_id bigint NOT NULL,
    id bigint NOT NULL,
    description text,
    nom character varying(255),
    site_recommandation character varying(255),
    status character varying(255),
    url_offre character varying(255),
    CONSTRAINT job_status_check CHECK (((status)::text = ANY ((ARRAY['EN_COURS'::character varying, 'REFUSE'::character varying, 'ACCEPTE'::character varying, 'ARCHIVE'::character varying])::text[])))
);


ALTER TABLE public.job OWNER TO postgres;

--
-- Name: job_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_skill; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_skill (
    job_id bigint NOT NULL,
    skill_id bigint NOT NULL
);


ALTER TABLE public.job_skill OWNER TO postgres;

--
-- Name: skill; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.skill (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.skill OWNER TO postgres;

--
-- Name: skill_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.skill ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




--
-- Name: entreprise_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.entreprise_id_seq', 58, true);


--
-- Name: job_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.job_id_seq', 31, true);


--
-- Name: skill_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.skill_id_seq', 530, true);


--
-- Name: entreprise entreprise_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entreprise
    ADD CONSTRAINT entreprise_pkey PRIMARY KEY (id);


--
-- Name: job job_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT job_pkey PRIMARY KEY (id);


--
-- Name: job_skill job_skill_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_skill
    ADD CONSTRAINT job_skill_pkey PRIMARY KEY (job_id, skill_id);


--
-- Name: skill skill_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.skill
    ADD CONSTRAINT skill_pkey PRIMARY KEY (id);


--
-- Name: job_skill fk9ix4wg520ii2gu2felxdhdup6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_skill
    ADD CONSTRAINT fk9ix4wg520ii2gu2felxdhdup6 FOREIGN KEY (job_id) REFERENCES public.job(id);


--
-- Name: job_skill fkj33qbbf3vk1lvhqpcosnh54u1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_skill
    ADD CONSTRAINT fkj33qbbf3vk1lvhqpcosnh54u1 FOREIGN KEY (skill_id) REFERENCES public.skill(id);


--
-- Name: job fkpaipfyvwj7fo654ri6uuvx6he; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT fkpaipfyvwj7fo654ri6uuvx6he FOREIGN KEY (entreprise_id) REFERENCES public.entreprise(id);


--
-- PostgreSQL database dump complete
--

